before_install:
 - chmod +x gradlew

language: android
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
script: ./gradlew build check